### ISSUE TITLE
this seems to solve the no git log problem on Windows: git --no-pager less

### ISSUE THREAD

**Issue by bast** [coderefinery/installation#113]

**Comment by bast** [comment]
This was anaconda prompt not working with git log.

**Comment by bast** [comment]
It seems these two are the solution:
```
$ git config --global pager.diff off
$ git config --global pager.config off
```

**Comment by rkdarst** [comment]
This should always work: `git --no-pager [subcommand ...]`

This should configure should make it permanently work, but you have to individually find all the commands that might use a pager:
```
$ git config --global pager.log off
$ git config --global pager.diff off
$ git config --global pager.show off
$ git config --global pager.config off
$ git config --global pager.stash off
$ git config --global pager.help off
$ git config --global pager.blame off
```
Someone could see if `git config --global core.pager off` works, but the docs don't say that is a supported option.

The `git log` UI without a pager will be bad, when everything scrolls off the screen because there is too much output.  Hopefully that's OK here since we don't have too many commits in this course...

**Comment by juholehtonen** [comment]
This also fixed `git branch`not showing output. So tried with `git --no-pager branch` and then set it in the configuration.

**Comment by rkdarst** [comment]
Comment above updated with those commands

The manual page says that `git config --global core.pager cat` should disable it for all commands - but does this work on operating systems without `cat` (windows not from git-bash)?

**Comment by bast** [comment]
Although we recommend now Git Bash, we should add this to troubleshooting hints on the install page.
