### ISSUE TITLE
give time estimate for installation steps.

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/installation#128]
from data-analysis-workflows: "could you estimate the time needed for each step of the installation? It makes a difference if it's minutes or hours".  Related to underestimating the time needed to do it properly.

About a different course, but could be relevant here too.

**Comment by bast** [comment]
Dropping this because an install step can take 1 minute or 40 minutes and it can be discouraging for two reasons:
- if if we indicate a lot less than it takes, one can feel a bit bad
- if we indicate a lot more than it takes, it can discourage from even trying (when I see that this takes hours)

See also #155.
